In [18]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split
import mlflow

In [32]:
from sklearn import set_config
set_config(transform_output = "pandas")

In [33]:
pd.set_option('display.max_columns', 100)

In [34]:
data = pd.read_csv(("/Users/aryagupta/Desktop/food-delivery-estimation/food_time_prediction_using_mlops/data/interim/train_interim.csv"))
data.head()

,Unnamed: 0,id,person_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,order_time,order_picked,weather,traffic,vehicle_condition,order_type,vehical_type,multiple_deliveries,is_festival,city_category,time,city,day,month,year,day_of_week,is_weekend,order_time_hour,order_time_of_day,pickup_time,distance
0,0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,2025-05-23 11:30:00,2025-05-23 11:45:00,sunny,high,2,snack,motorcycle,0.0,no,urban,24,INDO,19,3,2022,Saturday,1,11.0,morning,15.0,3.025149
1,1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,2025-05-23 19:45:00,2025-05-23 19:50:00,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,BANG,25,3,2022,Friday,0,19.0,evening,5.0,20.183530
2,2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,2025-05-23 08:30:00,2025-05-23 08:45:00,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,BANG,19,3,2022,Saturday,1,8.0,morning,15.0,1.552758
3,3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,2025-05-23 18:00:00,2025-05-23 18:10:00,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,COIMB,5,4,2022,Tuesday,0,18.0,evening,10.0,7.790401
4,4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,2025-05-23 13:30:00,2025-05-23 13:45:00,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,CHEN,26,3,2022,Saturday,1,13.0,afternoon,15.0,6.210138

In [23]:
data.columns

Index(['Unnamed: 0', 'id', 'person_id', 'age', 'ratings',
       'restaurant_latitude', 'restaurant_longitude', 'delivery_latitude',
       'delivery_longitude', 'order_date', 'order_time', 'order_picked',
       'weather', 'traffic', 'vehicle_condition', 'order_type', 'vehical_type',
       'multiple_deliveries', 'is_festival', 'city_category', 'time', 'city',
       'day', 'month', 'year', 'day_of_week', 'is_weekend', 'order_time_hour',
       'order_time_of_day', 'pickup_time', 'distance'],
      dtype='object')

In [29]:
drop_feature = ['Unnamed: 0', 'id', 'person_id', 'restaurant_latitude', 'restaurant_longitude', 'delivery_latitude',
               'delivery_longitude', 'order_date', 'time', 'day', 'city', 'day_of_week', 'month', 'order_time', 
               'order_picked']

data.drop(drop_feature, axis = 1, inplace = True)

In [31]:
data.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
order_type                0
vehical_type              0
multiple_deliveries     993
is_festival             228
city_category          1198
year                      0
is_weekend                0
order_time_hour        1640
order_time_of_day         0
pickup_time            1640
distance               4029
dtype: int64

In [ ]:
# city_type	1198
time_taken	0
# is_weekend	0
# pickup_time_minutes	1640
order_time_of_day	2070
# distance	3630
distance_type	3630

In [30]:
data.sample(5)

,age,ratings,weather,traffic,vehicle_condition,order_type,vehical_type,multiple_deliveries,is_festival,city_category,year,is_weekend,order_time_hour,order_time_of_day,pickup_time,distance
28626,39.0,4.0,cloudy,jam,1,snack,motorcycle,2.0,no,metropolitian,2022,0,20.0,night,15.0,19.975153
24648,26.0,5.0,stormy,medium,1,drinks,motorcycle,1.0,no,metropolitian,2022,1,17.0,evening,15.0,14.022322
23146,32.0,4.8,windy,medium,1,snack,motorcycle,1.0,no,metropolitian,2022,1,17.0,evening,10.0,7.649724
3550,27.0,4.6,cloudy,jam,2,drinks,scooter,2.0,yes,metropolitian,2022,1,21.0,night,5.0,19.916260
21517,30.0,4.7,sunny,jam,1,buffet,motorcycle,0.0,no,metropolitian,2022,1,19.0,evening,15.0,13.972053